---
- name: Change user and permission
  hosts: all
  tasks:
  - name: Change user and perm
      win_acl:
        user: user_Abby
        path: C:\Temp\test.conf
        type: allow
        rights: FullControl