---
- name: Change user and permission
  hosts: all
  tasks:
  - name: Change user to Abby and permission
    win_acl:
      user: Abby
      path: C:\Temp\test.conf
      type: allow
      rights: FullControl