---
- name: Create user and group and profile
  hosts: all
  tasks:
  - name: Create a new group
    win_group:
      name: RH.gg
      description: Deploy Group
      state: present

  - name: Add the user 'user_Abby' into group 'RH.gg'
    user:
      name: user_Abby
      group: RH.gg