---
- name: Testing handlers
  hosts: all
  tasks:
  - name: Install Dotnet4.6.1
    win_chocolatey:
      name: vlc
      state: present
    notify: reboot
  - name: failing the task
    debug:
      msg: failing the task as testing requires
      failed_when: true
  - name: This is another task
    debug:
      final task
  handlers:
  - name: reboot
    win_reboot: