---
- name: Testing handlers
  hosts: all
  tasks:
  - name: winrar
    win_chocolatey:
      name: winrar
      state: present
    notify: reboot
  - name: failing the task
    debug:
      msg: failing the task as testing requires
    failed_when: true
    ignore_errors: true
  - name: This is another task
    debug:
      msg: final task
  handlers:
  - name: reboot
    win_reboot: