---
- name: Testing handlers
  hosts: all
  tasks:
  - name: 7zip
    win_chocolatey:
      name: 7zip
      state: present
    notify: reboot
  - name: failing the task
    debug:
      msg: failing the task as testing requires
    failed_when: true
  - name: This is another task
    debug:
      msg: final task
  handlers:
  - name: reboot
    win_reboot: