---
- name: Testing handlers
  hosts: all
  tasks:
  - name: Install Dotnet4.6.1
    win_chocolatey:
      name: vlc
      state: present
    notify: reboot
  - name: failing the task
    fail:
      msg: failing the task as testing requires

  handlers:
  - name: reboot
    win_reboot: